---
- name: EFS provisioning
  community.aws.efs:
    aws_access_key: "{{ cico_efs_access_key }}"
    aws_secret_key: "{{ cico_efs_secret_key }}"
    region: "{{ cico_region }}"
    state: present
    name: "{{ cico_project_name }}"
    tags:
      Name: "{{ cico_project_name }}"
      cico: "{{ cico_project_name }}"
    targets:
      - subnet_id: "{{ cico_subnet_id }}"
        security_groups: ["{{ cico_security_group }}"]
  tags:
    - create_efs
  register: create_efs_filesystem_response

- name: Print the response from the AWS EFS FileSystem creation
  debug:
    msg: "{{ create_efs_filesystem_response }}"

- name: Create the EFS AccessPoint
  communishift_storage_efs:
    project_name: "{{ cico_project_name }}"
    aws_access_key_id: "{{ cico_efs_access_key }}"
    aws_secret_access_key: "{{ cico_efs_secret_key }}"
    aws_region: "{{ cico_region }}"
    aws_efs_filesystem_id: >-
      {{create_efs_filesystem_response['efs']['file_system_id']}}
  register: create_efs_accesspoint_response
  ignore_errors: true

- name: Print the response from the AWS EFS AccessPoint creation
  debug:
    msg: "{{ create_efs_accesspoint_response }}"

- name: Store facts
  set_fact:
    accesspoint_id: "{{create_efs_accesspoint_response['accesspoint_id']}}"
    filesystem_id: "{{create_efs_filesystem_response['efs']['file_system_id']}}"
